# Build and publish staging/test

trigger:
  branches:
    include:
      - develop

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  solutionPath: '**/Assessments.Web.csproj'

steps:

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '9.x'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        New-Item $(Build.SourcesDirectory)/Assessments.Web/BuildNumber.txt -Force
        Set-Content $(Build.SourcesDirectory)/Assessments.Web/BuildNumber.txt '$(Build.BuildNumber)'

  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: 'build'
      projects: $(solutionPath)
      configuration: $(buildConfiguration)

  - task: DotNetCoreCLI@2
    displayName: 'Publish and zip'
    inputs:
      command: publish
      publishWebProjects: False
      projects: $(solutionPath)
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: True

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'Assessments'
      publishLocation: 'Container'
